publication_index:
    path:     /
    defaults: { _controller: "PublicationBundle:Publication:index" }
    methods:  GET

publication_show:
    path:     /{id}/show
    defaults: { _controller: "PublicationBundle:Publication:show" }
    methods:  GET

publication_new:
    path:     /new
    defaults: { _controller: "PublicationBundle:Publication:new" }
    methods:  [GET, POST]

publication_edit:
    path:     /{id}/edit
    defaults: { _controller: "PublicationBundle:Publication:edit" }
    methods:  [GET, POST]

publication_delete:
    path:     /{id}/delete
    defaults: { _controller: "PublicationBundle:Publication:delete" }
    methods:  DELETE
