<?php

namespace AppBundle\Repository;

/**
 * DemandeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeurRepository extends \Doctrine\ORM\EntityRepository
{
}
