<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.qgay0fs' shared service.

return $this->services['service_locator.qgay0fs'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['validate' => function () {
    $f = function (\AppBundle\Service\Validate $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\\Service\\Validate']) ? $this->services['AppBundle\\Service\\Validate'] : $this->load('getValidateService.php')) && false ?: '_'});
}]);
