<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Service\Validate' shared autowired service.

include_once $this->targetDirs[3].'\\src\\AppBundle\\Service\\Validate.php';

return $this->services['AppBundle\\Service\\Validate'] = new \AppBundle\Service\Validate(${($_ = isset($this->services['validator']) ? $this->services['validator'] : $this->getValidatorService()) && false ?: '_'}, ${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
