<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXzhwcfn\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXzhwcfn/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXzhwcfn.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXzhwcfn\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXzhwcfn\appDevDebugProjectContainer([
    'container.build_hash' => 'Xzhwcfn',
    'container.build_id' => 'c98e2254',
    'container.build_time' => 1591742048,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXzhwcfn');
